### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by weihao** [bolt-rip/Dockerizedcraft#4]
[04:40:22 INFO] [org.apache.http.impl.execchain.RetryExec]: Retrying request to {}->unix://localhost:80
[04:40:22 INFO] [org.apache.http.impl.execchain.RetryExec]: I/O exception (java.net.SocketException) caught when processing request to {}->unix://localhost:80: Connection refused
[04:40:22 INFO] [org.apache.http.impl.execchain.RetryExec]: Retrying request to {}->unix://localhost:80
[04:40:22 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@28c86134, id=27, owner=de.craftmania.dockerizedcraft.DockerizedCraft@36224f93, task=de.craftmania.dockerizedcraft.DockerizedCraft$$Lambda$717/0x00000008006cdc40@537ca28e, delay=0, period=0, running=true) encountered an exception
javax.ws.rs.ProcessingException: java.net.SocketException: Connection refused
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:496) ~[?:?]
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278) ~[?:?]
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:787) ~[?:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[?:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[?:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229) ~[?:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414) ~[?:?]
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:785) ~[?:?]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438) ~[?:?]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329) ~[?:?]
        at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:47) ~[?:?]
        at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:19) ~[?:?]
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23) ~[?:?]
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[?:?]
        at de.craftmania.dockerizedcraft.container.inspector.docker.DockerContainerInspector.runContainerInspection(DockerContainerInspector.java:36) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.SocketException: Connection refused
        at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method) ~[?:?]
        at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:251) ~[?:?]
        at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:144) ~[?:?]
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.connect(ApacheUnixSocket.java:62) ~[?:?]
        at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:74) ~[?:?]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]      
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[Waterfall-1.17-437.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450) ~[?:?]
        ... 18 more

```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by unixfox** [comment]
It's a fork for supporting Kubernetes, unfortunately we don't support Docker. I can't help you.
